(define-library (hamt-map-test)
  (import (scheme base)
	  (chibi test)
	  (hamt)
	  (hamt-map)
	  (hamt-misc)
	  (only (srfi 1) fold)
	  (only (srfi 151) bit-count))
  (export run-hamt-map-tests)
  (include "hamt-map-test.scm"))