test:
	CHIBI_MODULE_PATH=.:../.. chibi-scheme -m hamt-test -e '(run-hamt-core-tests)'
	CHIBI_MODULE_PATH=.:../.. chibi-scheme -m hamt-misc-test -e '(run-hamt-misc-tests)'
	CHIBI_MODULE_PATH=.:../.. chibi-scheme -m hamt-map-test -e '(run-hamt-map-tests)'
	CHIBI_MODULE_PATH=.:../.. chibi-scheme -m vector-edit-test -e '(run-vector-edit-tests)'
